plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: disable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "spec/dummy/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Rails:
  Enabled: true

Layout/LineLength:
  Max: 90
  Exclude:
    - "app/views/**/*"
    - "db/migrate/**/*"
    - "spec/**/*"

Layout/HashAlignment:
  EnforcedColonStyle: key
  EnforcedHashRocketStyle: table
  EnforcedLastArgumentHashStyle: always_inspect

Layout/ExtraSpacing:
  AllowForAlignment: true

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "db/**/*"

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "spec/**/*.rb"
    - "db/**/*"

Metrics/ClassLength:
  Max: 150
  Exclude:
    - "spec/**/*.rb"

Metrics/ModuleLength:
  Max: 150

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/DescribedClass:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
