plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Include:
    - "app/**/*.rb"
    - "config/**/*.rb"
    - "db/**/*.rb"
    - "lib/**/*.rb"
    - "spec/**/*.rb"
    - "Rakefile"
  Exclude:
    - "spec/dummy/**/*"
    - "vendor/**/*"
    - "bin/**/*"
    - "*.gemspec"
    - "Gemfile"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 30
  Exclude:
    - "db/**/*"

Metrics/MethodLength:
  Max: 50

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

Lint/EmptyClass:
  Enabled: false
