require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - "spec/dummy/**/*"
    - "bin/**/*"
    - "*.gemspec"
    - "Gemfile"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Exclude:
    - "db/**/*"

Metrics/MethodLength:
  Max: 50

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 3

Lint/EmptyClass:
  Enabled: false

